# Do not create pipelines for non-default branches
workflow:
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
      when: never

include: ".pipeline-common.yml"

stages:
  - child-pipelines

aea:
  stage: child-pipelines
  trigger:
    include:
      - local: .pipeline-aea.yml
    strategy: depend
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  variables:
    PARENT_CI_COMMIT_TAG: $CI_COMMIT_TAG
    PARENT_CI_PIPELINE_SOURCE: $CI_PIPELINE_SOURCE
    PARENT_CI_COMMIT_BRANCH: $CI_COMMIT_BRANCH

hpc:
  stage: child-pipelines
  trigger:
    include:
      - local: .pipeline-hpc.yml
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  variables:
    PARENT_CI_PIPELINE_SOURCE: $CI_PIPELINE_SOURCE
    PARENT_CI_COMMIT_BRANCH: $CI_COMMIT_BRANCH

win:
  stage: child-pipelines
  trigger:
    include:
      - local: .pipeline-win.yml
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  variables:
    PARENT_CI_PIPELINE_SOURCE: $CI_PIPELINE_SOURCE
    PARENT_CI_COMMIT_BRANCH: $CI_COMMIT_BRANCH

mac:
  stage: child-pipelines
  trigger:
    include:
      - local: .pipeline-mac.yml
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  variables:
    PARENT_CI_PIPELINE_SOURCE: $CI_PIPELINE_SOURCE
    PARENT_CI_COMMIT_BRANCH: $CI_COMMIT_BRANCH
