# Required for HPC Jacamar Runner
default:
  id_tokens:
    SITE_ID_TOKEN:
      aud: https://re-git.lanl.gov

stages:
  - environment
  - test

include: ".pipeline-common.yml"

hpc-environment:
  extends:
    - .linux-cached-environment
    - .build-cached-environment
  stage: environment
  rules:
    - if: $CI_PIPELINE_SOURCE == "parent_pipeline"
  variables:
    conda_installation: "/udsl/udsl1/hpcsoft/common/x86_64/anaconda/2024.10-python-3.12"
    aea_compute_path: "/usr/projects/ea/aea_compute"
    ci_environment_path: "/lustre/roscratch1/${GITLAB_USER_LOGIN}"
    scratch_root: "/lustre/roscratch1"
    abaqus_command_prefix: "/usr/projects/ea/abaqus/Commands"
    cubit_command_prefix: "/usr/projects/ea/Cubit"
  tags:
    - rocinante
    - shell

hpc-fast-test:
  extends:
    - .linux-cached-environment
  stage: test
  rules:
    - if: $CI_PIPELINE_SOURCE == "parent_pipeline"
  variables:
    conda_installation: "/udsl/udsl1/hpcsoft/common/x86_64/anaconda/2024.10-python-3.12"
    aea_compute_path: "/usr/projects/ea/aea_compute"
    ci_environment_path: "/lustre/roscratch1/${GITLAB_USER_LOGIN}"
    scratch_root: "/lustre/roscratch1"
    abaqus_command_prefix: "/usr/projects/ea/abaqus/Commands"
    cubit_command_prefix: "/usr/projects/ea/Cubit"
  script:
    # TODO: Remove HPC specific fast-test script when HPC CI TeXLive builds are fixed
    # https://re-git.lanl.gov/aea/python-projects/waves/-/issues/891
    # Job variables
    - echo ${abaqus_command_prefix}
    - echo ${cubit_command_prefix}
    - if [[ -z ${abaqus_command_prefix} ]]; then exit 1; fi
    - if [[ -z ${cubit_command_prefix} ]]; then exit 1; fi
    - echo ${PARENT_CI_PIPELINE_SOURCE}
    # Job commands
    - scons pytest systemtest --keep-going --unconditional-build --abaqus-command=${abaqus_command_prefix}/abq2024 --cubit-command=${cubit_command_prefix}/Cubit-16.16/cubit
    - if [[ $PARENT_CI_PIPELINE_SOURCE == "schedule" ]]; then scons systemtest --keep-going --unconditional-build --abaqus-command=${abaqus_command_prefix}/abq2023 --cubit-command=${cubit_command_prefix}/Cubit-16.12/cubit; fi
  tags:
    - rocinante
    - batch
