stages:
  - test

include: ".pipeline-common.yml"

before_script:
  - $PSVersionTable
  # Common job variables
  - $conda_installation="C:\ProgramData\anaconda3"
  - $prefix="$pwd\conda-environment"
  - $conda_pkgs_dirs="$pwd\pkgs"
  - Write-Output $conda_installation
  - Write-Output $prefix
  - Write-Output $conda_pkgs_dirs
  - if (!(Test-Path -Path $conda_installation -PathType Container)) { exit 1 }
  - if ([string]::IsNullOrEmpty($prefix)) { exit 1 }
  # Environment creation
  - $env:CONDA_PKGS_DIRS=$conda_pkgs_dirs
  - (& "$conda_installation\Scripts\conda.exe" "shell.powershell" "hook") | Out-String | ?{$_} | Invoke-Expression
  - conda info
  - conda env create --prefix $prefix --file environment-win.yml --yes
  - conda activate $prefix

win-fast-test:
  extends:
    - .fast-test-no-third-party
  stage: test
  rules:
    - if: $PARENT_CI_PIPELINE_SOURCE == "schedule"
    - if: $PARENT_CI_PIPELINE_SOURCE == "merge_request_event"
  tags:
    - powershell
    - aea

win-conda-build:
  stage: test
  variables:
    GIT_STRATEGY: clone
    recipe_directory: "recipe"
  rules:
    - if: $PARENT_CI_PIPELINE_SOURCE == "schedule"
    - if: $PARENT_CI_PIPELINE_SOURCE == "merge_request_event"
  script:
    # Job variables
    - Write-Output $recipe_directory
    - if ([string]::IsNullOrEmpty($recipe_directory)) { exit 1 }
    # Job commands
    - $env:VERSION=python -m setuptools_scm
    - conda mambabuild $recipe_directory --channel fierromechanics --channel conda-forge --no-anaconda-upload
  tags:
    - powershell
    - aea

win-pip-build:
  stage: test
  variables:
    GIT_STRATEGY: clone
    distribution_name: "waves"
  script:
    # Job variables
    - scons pyproject.toml
    - $version=python -m setuptools_scm
    - Write-Output $distribution_name
    - Write-Output $version
    # Job commands
    # Conda CI environment active
    - scons install --distribution-name=${distribution_name}
    - python -m venv pip-build-test
    - pip-build-test\Scripts\Activate.ps1
    # Python venv environment active
    - python -m pip install --verbose --disable-pip-version-check --require-virtualenv --no-cache-dir build\dist\$distribution_name-$version.tar.gz pytest pytest-xdist
    - cd pip-build-test\Lib\site-packages\waves
    - python -m pytest -vvv -n 4 -m "not systemtest"
  rules:
    - if: $PARENT_CI_PIPELINE_SOURCE == "schedule"
    - if: $PARENT_CI_PIPELINE_SOURCE == "merge_request_event"
  tags:
    - powershell
    - aea
