include: ".pipeline-common.yml"

stages:
  - test

default:
  tags:
    - macos
    - pn2301275

mac-developer-test:
  extends:
    - .nix-job-environment
    - .developer-test-no-third-party
  stage: test
  rules:
    - if: $PARENT_CI_PIPELINE_SOURCE == "schedule"
    - if: $PARENT_CI_PIPELINE_SOURCE == "merge_request_event"
  variables:
    conda_installation: "/Users/gitlab-runner/anaconda3"

mac-conda-build:
  extends:
    - .nix-job-environment
    - .conda-build
  stage: test
  rules:
    - if: $PARENT_CI_PIPELINE_SOURCE == "schedule"
    - if: $PARENT_CI_PIPELINE_SOURCE == "merge_request_event"
  variables:
    conda_installation: "/Users/gitlab-runner/anaconda3"
    environment_file: "conda-build.yml"
    recipe_directory: "recipe"

mac-pip-build:
  extends:
    - .nix-job-environment
    - .pip-build
  stage: test
  rules:
    - if: $PARENT_CI_PIPELINE_SOURCE == "schedule"
    - if: $PARENT_CI_PIPELINE_SOURCE == "merge_request_event"
  variables:
    conda_installation: "/Users/gitlab-runner/anaconda3"
    environment_file: "pip-build.yml"
