stages:
  - test

include: ".pipeline-common.yml"

mac-fast-test:
  extends:
    - .nix-before-script
    - .fast-test-no-third-party
  stage: test
  rules:
    - if: $PARENT_CI_PIPELINE_SOURCE == "schedule"
    - if: $PARENT_CI_PIPELINE_SOURCE == "merge_request_event"
  variables:
    conda_installation: "/Users/gitlab-runner/anaconda3"
  tags:
    - macos
    - pn2301275

mac-conda-build:
  extends:
    - .nix-before-script
    - .conda-build
  stage: test
  rules:
    - if: $PARENT_CI_PIPELINE_SOURCE == "schedule"
    - if: $PARENT_CI_PIPELINE_SOURCE == "merge_request_event"
  variables:
    conda_installation: "/Users/gitlab-runner/anaconda3"
    recipe_directory: "recipe"
  tags:
    - macos
    - pn2301275

mac-pip-build:
  extends:
    - .nix-before-script
    - .pip-build
  stage: test
  rules:
    - if: $PARENT_CI_PIPELINE_SOURCE == "schedule"
    - if: $PARENT_CI_PIPELINE_SOURCE == "merge_request_event"
  variables:
    conda_installation: "/Users/gitlab-runner/anaconda3"
  tags:
    - macos
    - pn2301275
