{% set name = "waves" %}
{% set version = VERSION %}

package:
  name: {{ name|lower }}
  # TODO: Figure out how to use pyproject.toml and a Conda build Jinja template
  version: {{ version }}

source:
  path: '..'

# NOTE: CANNOT use noarch builds. conda-build will not use python variants if the package is marked "noarch: python"
build:
  number: 0
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  entry_points:
    - odb_extract = waves._abaqus.odb_extract:main
    - waves = waves._main:main

requirements:
  host:
    # Force consistency in the Python build version
    - python {{ python }}
    - python-build
    - pip
    # Force consistency in the Python build version
    - scons {{ scons }}
    - setuptools >=64
    - setuptools_scm >=8
    - sphinx >=7.1
    - sphinx-argparse
    - sphinx-copybutton >=0.5.1
    - sphinx-book-theme
    - sphinx-design
    - sphinxcontrib-bibtex
  run:
    # Force a Python variant package build
    - python {{ python }}
    - h5netcdf
    - h5py
    - matplotlib-base
    - networkx
    - numpy
    - pyyaml
    - salib >=1
    - scipy >=1.7
    # Force an SCons variant package build
    - scons {{ scons }}
    - xarray

test:
  requires:
    # Force a Python variant package test
    - python {{ python }}
    - pip
    - pytest>=6
    - pytest-xdist
  imports:
    - waves

about:
  home: https://github.com/lanl-aea/waves
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: 'Computational science and engineering parameteric study workflows'
  description: |
    WAVES (LANL code C23004) is a computational science and engineering workflow tool that integrates parametric studies
    with traditional software build systems.
  doc_url: https://lanl-aea.github.io/waves/index.html
  dev_url: https://github.com/lanl-aea/waves
